language: cpp

dist: trusty

before_install:
  - eval "${MATRIX_EVAL}"

install:
  # Install conan
  - pip3 install --user -q conan
  # Automatic detection of your arch, compiler, etc.

script:
  - mkdir build && cd build
  - conan install .. --build -s compiler.libcxx=libstdc++11
  - cmake ..
  - cmake --build .
  - ./bin/test_hello

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - python3
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
