language: cpp

install:
  # Install conan
  - pip install --user -q conan -s compiler.libcxx=libstdc++11
  # Automatic detection of your arch, compiler, etc.
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build=missing
  - cmake ..
  - cmake --build .
  - ./bin/test_hello
